### ISSUE TITLE
Request: Inconsistent behaviour of applying Cover vs Flat-Footed with keyboard shortcuts

### ISSUE THREAD

**Issue by jocolamarco** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#8]
Currently, when applying Flat-Footed status via keyboard shortcut (e.g. 'F'), it only needs the token to be hovered and not selected.
![imagem](https://user-images.githubusercontent.com/45291719/151980762-d754a303-069d-4900-8e3d-49561193e342.png)

However, for Cover, it only works on selected token rather than hovered.
![imagem](https://user-images.githubusercontent.com/45291719/151981025-b925e135-699f-4890-92bd-bc48045eae96.png)

Is it possible to make them behave in the same way? Is there a rationale behind this implementation?

Core Version: 9.245

System: pf2e 3.3.1.10273 (The PF2e System Developers) 

pf2e-f-is-for-flatfooted 3.3.2 (DrentalBot <drentalbot@crumblinggiant.com>)

**Comment by Drental** [comment]
that is deliberate because I wanted it to always be the same, using the selected token, so that players could use the keybinds.

the Flatfooted Keybind was historically a hover Keybind though. I can maybe make an additional one and add a setting to use hover or selected tokens on all the normal ones (I won't change the F Keybind without a very compelling reason ever)

**Comment by jocolamarco** [comment]
F keybind has the same behaviour as T for Targeting which I like

OK, I get your point of C as it allows players to apply to themselves. Thanks for the explanation
